/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#0d631b',
        'primary-hover': '#0b5216',
        'primary-container': '#2e7d32',
        'on-primary': '#ffffff',
        'on-primary-container': '#cbffc2',
        'primary-fixed': '#a3f69c',
        'primary-fixed-dim': '#88d982',
        'on-primary-fixed': '#002204',
        'on-primary-fixed-variant': '#005312',
        secondary: '#126d27',
        'secondary-container': '#9cf49c',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#19722b',
        'secondary-fixed': '#9ff79f',
        'secondary-fixed-dim': '#83da85',
        tertiary: '#335f3a',
        'tertiary-container': '#4b7850',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ccfecd',
        'tertiary-fixed': '#bdefbe',
        'tertiary-fixed-dim': '#a2d3a4',
        surface: '#f8f9ff',
        'surface-dim': '#d0dbed',
        'surface-bright': '#f8f9ff',
        'surface-variant': '#d9e3f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e6eeff',
        'surface-container-high': '#dee9fc',
        'surface-container-highest': '#d9e3f6',
        'on-surface': '#121c2a',
        'on-surface-variant': '#40493d',
        'inverse-surface': '#27313f',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#88d982',
        outline: '#707a6c',
        'outline-variant': '#bfcaba',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f8f9ff',
        'on-background': '#121c2a',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'card': '12px',
        'pill': '9999px',
      },
      boxShadow: {
        'soft': '0 2px 10px rgba(0, 0, 0, 0.04), 0 1px 3px rgba(0, 0, 0, 0.02)',
        'card': '0 4px 20px -2px rgba(18, 28, 42, 0.08)',
        'dropdown': '0 10px 30px -5px rgba(18, 28, 42, 0.15)',
        'glow': '0 0 15px rgba(13, 99, 27, 0.25)',
      }
    },
  },
  plugins: [],
}
